# -*- coding: utf-8 -*-
"""IssaAssi-MLProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1szTAD08EzKbXcgSyicl6ndMFVXXG9Big
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt

df = pd.read_csv("input_tokens.csv")

scam_cond = (
    (df["pass_report"] < 45) |
    (df["t10_percent"] > 30) |
    (df["liquidity_usd"].fillna(0) < 1_000) |
    (df["fdv"].fillna(0) < 40_000)
)

df["is_scam"] = np.where(scam_cond, 1, 0)

print("Dataset Info:")
print(df.info())
print(df.head())

df.dropna(subset=["price_h24"], inplace=True)
# drop any rows with no activity in the last 24h
df.drop('address', axis=1, inplace=True)
# drop address as it is irrelevant now
print(df.info())
print(df["is_scam"].value_counts())

y = df['is_scam']
x = df.drop('is_scam', axis=1)

numerical_cols = ['t10_percent', 'txns_h24', 'volume_h24',
'volume_m5', 'price_h24', 'price_m5', 'liquidity_usd', 'fdv', 'pass_report']

scaler = StandardScaler()
x[numerical_cols] = scaler.fit_transform(x[numerical_cols])

print(x.head())
print(y.head())

from sklearn.linear_model import LogisticRegression

# Split the dataset
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# Initialize and train Logistic Regression with balanced class weights
log_reg = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)
log_reg.fit(x_train, y_train)

# Predict
y_pred = log_reg.predict(x_test)

# Evaluation
accuracy = accuracy_score(y_test, y_pred)
matrix = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

# Output results
print("Model Evaluation:")
print(f"Accuracy: {accuracy}")
print("Confusion Matrix:")
print(matrix)
print("\nClassification Report:")
print(report)

new_instance = {
  #trump coin: expected is scam because a large portion of the liquidity of
  #this coin was pulled when it was at 80$, its sitting at 13 now. Also top10% hold 91%
  't10_percent': 91.536,
  'txns_h24': 17185,
  'volume_h24': 127155747.48,
  'volume_m5': 114408.78,
  'price_h24': -9.94,
  'price_m5': -0.7,
  'liquidity_usd': 397306989.42,
  'fdv': 13797507626.6287,
  'pass_report':59.6330275229358,
}

df_new = pd.DataFrame([new_instance])
df_new[numerical_cols] = scaler.transform(df_new[numerical_cols])
prediction = log_reg.predict(df_new)

print(f"Prediction for new instance: {'Scam' if prediction[0] == 1 else 'Not Scam'}")

from sklearn.linear_model import LogisticRegression
import numpy as np
import matplotlib.pyplot as plt

error_rates = []
C_values = np.logspace(-3, 3, 20)  # 20 values from 0.001 to 1000

for c in C_values:
    log_reg_temp = LogisticRegression(C=c, class_weight='balanced', max_iter=1000, random_state=42)
    log_reg_temp.fit(x_train, y_train)
    y_pred = log_reg_temp.predict(x_test)
    error = np.mean(y_pred != y_test)
    error_rates.append(error)

plt.plot(C_values, error_rates, marker='o')
plt.xscale('log')  # because C is logarithmic scale
plt.xlabel('C Value (Inverse Regularization Strength)')
plt.ylabel('Error Rate')
plt.title('Error Rate vs C Value for Logistic Regression')
plt.grid(True)
plt.show()